class Country {
  final String name;
  final String code;
  final String? flag;

  const Country({required this.name, required this.code, this.flag});
}

class GeoData {
  static const List<Country> countries = [
    Country(name: 'Afghanistan', code: 'AF', flag: '🇦🇫'),
    Country(name: 'Albania', code: 'AL', flag: '🇦🇱'),
    Country(name: 'Algeria', code: 'DZ', flag: '🇩🇿'),
    Country(name: 'Andorra', code: 'AD', flag: '🇦🇩'),
    Country(name: 'Angola', code: 'AO', flag: '🇦🇴'),
    Country(name: 'Argentina', code: 'AR', flag: '🇦🇷'),
    Country(name: 'Australia', code: 'AU', flag: '🇦🇺'),
    Country(name: 'Austria', code: 'AT', flag: '🇦🇹'),
    Country(name: 'Bahamas', code: 'BS', flag: '🇧🇸'),
    Country(name: 'Bahrain', code: 'BH', flag: '🇧🇭'),
    Country(name: 'Bangladesh', code: 'BD', flag: '🇧🇩'),
    Country(name: 'Belgium', code: 'BE', flag: '🇧🇪'),
    Country(name: 'Brazil', code: 'BR', flag: '🇧🇷'),
    Country(name: 'Canada', code: 'CA', flag: '🇨🇦'),
    Country(name: 'China', code: 'CN', flag: '🇨🇳'),
    Country(name: 'Colombia', code: 'CO', flag: '🇨🇴'),
    Country(name: 'Croatia', code: 'HR', flag: '🇭🇷'),
    Country(name: 'Cyprus', code: 'CY', flag: '🇨🇾'),
    Country(name: 'Czech Republic', code: 'CZ', flag: '🇨🇿'),
    Country(name: 'Denmark', code: 'DK', flag: '🇩🇰'),
    Country(name: 'Egypt', code: 'EG', flag: '🇪🇬'),
    Country(name: 'Finland', code: 'FI', flag: '🇫🇮'),
    Country(name: 'France', code: 'FR', flag: '🇫🇷'),
    Country(name: 'Germany', code: 'DE', flag: '🇩🇪'),
    Country(name: 'Greece', code: 'GR', flag: '🇬🇷'),
    Country(name: 'Hungary', code: 'HU', flag: '🇭🇺'),
    Country(name: 'Iceland', code: 'IS', flag: '🇮🇸'),
    Country(name: 'India', code: 'IN', flag: '🇮🇳'),
    Country(name: 'Indonesia', code: 'ID', flag: '🇮🇩'),
    Country(name: 'Ireland', code: 'IE', flag: '🇮🇪'),
    Country(name: 'Israel', code: 'IL', flag: '🇮🇱'),
    Country(name: 'Italy', code: 'IT', flag: '🇮🇹'),
    Country(name: 'Japan', code: 'JP', flag: '🇯🇵'),
    Country(name: 'Jordan', code: 'JO', flag: '🇯🇴'),
    Country(name: 'Mexico', code: 'MX', flag: '🇲🇽'),
    Country(name: 'Netherlands', code: 'NL', flag: '🇳🇱'),
    Country(name: 'New Zealand', code: 'NZ', flag: '🇳🇿'),
    Country(name: 'Norway', code: 'NO', flag: '🇳🇴'),
    Country(name: 'Philippines', code: 'PH', flag: '🇵🇭'),
    Country(name: 'Poland', code: 'PL', flag: '🇵🇱'),
    Country(name: 'Portugal', code: 'PT', flag: '🇵🇹'),
    Country(name: 'Russia', code: 'RU', flag: '🇷🇺'),
    Country(name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦'),
    Country(name: 'Singapore', code: 'SG', flag: '🇸🇬'),
    Country(name: 'South Africa', code: 'ZA', flag: '🇿🇦'),
    Country(name: 'South Korea', code: 'KR', flag: '🇰🇷'),
    Country(name: 'Spain', code: 'ES', flag: '🇪🇸'),
    Country(name: 'Sweden', code: 'SE', flag: '🇸🇪'),
    Country(name: 'Switzerland', code: 'CH', flag: '🇨🇭'),
    Country(name: 'Thailand', code: 'TH', flag: '🇹🇭'),
    Country(name: 'Turkey', code: 'TR', flag: '🇹🇷'),
    Country(name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪'),
    Country(name: 'United Kingdom', code: 'GB', flag: '🇬🇧'),
    Country(name: 'United States', code: 'US', flag: '🇺🇸'),
    Country(name: 'Vietnam', code: 'VN', flag: '🇻🇳'),
  ];

  static const Map<String, List<String>> majorCities = {
    'FR': ['Paris', 'Lyon', 'Marseille', 'Nice', 'Bordeaux', 'Toulouse', 'Strasbourg'],
    'IT': ['Rome', 'Venice', 'Florence', 'Milan', 'Naples', 'Turin', 'Palermo'],
    'JP': ['Tokyo', 'Kyoto', 'Osaka', 'Sapporo', 'Fukuoka', 'Hiroshima', 'Nagoya'],
    'US': ['New York', 'Los Angeles', 'Chicago', 'Miami', 'San Francisco', 'Las Vegas', 'Seattle', 'Boston', 'Austin'],
    'TH': ['Bangkok', 'Phuket', 'Chiang Mai', 'Pattaya', 'Koh Samui', 'Krabi'],
    'GB': ['London', 'Edinburgh', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Oxford'],
    'ES': ['Madrid', 'Barcelona', 'Seville', 'Valencia', 'Malaga', 'Bilbao', 'Granada'],
    'GR': ['Athens', 'Santorini', 'Mykonos', 'Crete', 'Rhodes', 'Thessaloniki'],
    'CH': ['Zurich', 'Geneva', 'Lucerne', 'Interlaken', 'Bern', 'Zermatt'],
    'IL': ['Tel Aviv', 'Jerusalem', 'Haifa', 'Eilat', 'Netanya', 'Beersheba', 'Tiberias'],
    'DE': ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Dresden'],
    'CA': ['Toronto', 'Vancouver', 'Montreal', 'Ottawa', 'Calgary', 'Quebec City'],
    'AU': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Cairns'],
    'BR': ['Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Salvador', 'Fortaleza'],
    'MX': ['Mexico City', 'Cancun', 'Guadalajara', 'Monterrey', 'Tulum'],
    'KR': ['Seoul', 'Busan', 'Incheon', 'Jeju City', 'Daegu'],
    'PT': ['Lisbon', 'Porto', 'Faro', 'Coimbra', 'Sintra'],
    'TR': ['Istanbul', 'Antalya', 'Ankara', 'Izmir', 'Cappadocia'],
    'AT': ['Vienna', 'Salzburg', 'Innsbruck', 'Hallstatt', 'Graz'],
  };
}
